┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ [debug] 18:51:51 861ms
│ This is a debug message
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ [info] 18:51:51 866ms
│ Application started
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ [warning] 18:51:51 867ms
│ This is a warning message
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ [error] 18:51:51 867ms
│ This is an error message
│
│ Type: _Exception
│ Message: Exception: Test error
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ [debug] 20:33:13 408ms
│ This is a debug message
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ [info] 20:33:13 414ms
│ Application started
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ [warning] 20:33:13 414ms
│ This is a warning message
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ [error] 20:33:13 414ms
│ This is an error message
│
│ Type: _Exception
│ Message: Exception: Test error
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
